name: Build Windows Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install python-docx
        pip install pillow  # 处理图标可能需要
        
    - name: Build executable
      run: |
        # 重命名主文件为更友好的名称
        ren main.py DocxReplacer.py
        
        # 使用 PyInstaller 打包
        pyinstaller --onefile --windowed --icon=app.ico --name "DocxReplacer" --add-data "app.ico;." DocxReplacer.py
        
    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
        
    - name: Install Inno Setup
      run: |
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait
        
    - name: Create installer script
      run: |
        # 创建安装脚本
        $issContent = @"
        [Setup]
        AppName=DocxReplacer
        AppVersion=2.0.0
        AppPublisher=Easy
        AppPublisherURL=https://fdianshuo@gmail.com
        DefaultDirName={autopf}\DocxReplacer
        DefaultGroupName=DocxReplacer
        OutputDir=.\Output
        OutputBaseFilename=DocxReplacer_Setup
        SetupIconFile=app.ico
        Compression=lzma2
        SolidCompression=yes
        PrivilegesRequired=lowest
        
        [Files]
        Source: "dist\DocxReplacer.exe"; DestDir: "{app}"; Flags: ignoreversion
        Source: "app.ico"; DestDir: "{app}"; Flags: ignoreversion
        
        [Icons]
        Name: "{group}\DocxReplacer"; Filename: "{app}\DocxReplacer.exe"; IconFilename: "{app}\app.ico"
        Name: "{commondesktop}\DocxReplacer"; Filename: "{app}\DocxReplacer.exe"; IconFilename: "{app}\app.ico"
        
        [Run]
        Filename: "{app}\DocxReplacer.exe"; Description: "运行 DocxReplacer"; Flags: postinstall nowait skipifsilent
        "@
        
        $issContent | Out-File -Encoding ASCII installer.iss
        
    - name: Build installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Installer
        path: Output\DocxReplacer_Setup.exe
